name: On push action

on:
  push:
    branches: '*'
    tags-ignore:
      - v*

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      -
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 --statistics --show-source .

  mypy:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      -
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          mypy .

  pytest:
    runs-on: ubuntu-latest
    needs: [flake8, mypy]
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      -
        name: Install dependences
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -
        name: Test
        run: |
          pytest --cov-report term-missing --cov=project --cov-report xml tests -vv
      -
        name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
