name: Release ci/cd

on:
  push:
    tags:
      - v*

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      -
        name: Install dependences
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy
      -
        name: Flake8
        run: flake8 --statistics --show-source .
      - name: Mypy
        run: mypy .

  testing:
    runs-on: ubuntu-latest
    needs: [linting]
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      -
        name: Install dependences
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      -
        run: pytest . -v

  build:
    runs-on: ubuntu-latest
    needs: [testing]
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fcp_3:alpine_${GITHUB_REF:11} -f Dockerfile .
      -
        name: Push image to docker.io
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fcp_3:alpine_${GITHUB_REF:11}
